---
- name: ensure MySQL is installed
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb
    - php5-mysql
  tags:
    - mysql
    - install

- name: Start the MySQL service
  action: service name=mysql state=started
  tags:
    - mysql
    - verify-state

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} 
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  tags:
    - mysql
    - install
  ignore_errors: yes   


- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  sudo: yes
  tags:
    - mysql
    - verify-state 

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - $ansible_hostname
  tags:
    - mysql
    - install
  sudo: yes

- name: remove the test database
  mysql_db: name=test state=absent
  tags:
    - mysql
    - install
  sudo: yes